spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: simulated-trading-user-service
          uri: lb://simulated-trading-user-service
          predicates:
            - Path=/user/**
        - id: simulated-trading-instrument-service
          uri: lb://simulated-trading-instrument-service
          predicates:
            - Path=/instrument/**
        - id: simulated-trading-order-service
          uri: lb://simulated-trading-order-service
          predicates:
            - Path=/order/**
        - id: simulated-trading-position-service
          uri: lb://simulated-trading-position-service
          predicates:
            - Path=/position/**
        - id: simulated-trading-trade-service
          uri: lb://simulated-trading-trade-service
          predicates:
            - Path=/trade/**
  application:
    name: simulated-trading-gateway
  main:
    web-application-type: reactive
  web:
    resources:
      add-mappings: true
server:
  port: 80