spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: simulated-trading-user-service
          uri: lb://simulated-trading-user-service
          predicates:
            - Path=/user/**
        - id: simulated-trading-instrument-service
          uri: lb://simulated-trading-instrument-service
          predicates:
            - Path=/instrument/**
        - id: simulated-trading-order-service
          uri: lb://simulated-trading-order-service
          predicates:
            - Path=/order/**
        - id: simulated-trading-position-service
          uri: lb://simulated-trading-position-service
          predicates:
            - Path=/position/**
        - id: simulated-trading-trade-service
          uri: lb://simulated-trading-trade-service
          predicates:
            - Path=/trade/**
  application:
    name: simulated-trading-gateway
  main:
    web-application-type: reactive
  web:
    resources:
      add-mappings: true
server:
  port: 80

#  ssl:
#    enabled: true
#    key-store: classpath:tomcat_https.keystore
#    key-store-type: JKS
#    key-store-password: 123456
  tomcat:
    threads:
      max: 400

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2